package synapticloop.b2.request;

// - - - - thoughtfully generated by synapticloop backblaze-b2-java-api - - - - 
//          with the use of synapticloop templar templating language
//                    (java-create-api.templar)

/**
 * <p>Downloads one file from B2.</p>
 * 
 * <p>The response contains the following headers, which contain the same information they did when the file was uploaded:</p>
 * 
 * 
 * This is the interaction class for the <strong>b2_download_file_by_id</strong> api calls, this was automatically
 * generated from the backblaze api documentation - which can be found here:
 * <a href="http://www.backblaze.com/b2/docs/b2_download_file_by_id.html">http://www.backblaze.com/b2/docs/b2_download_file_by_id.html</a>
 * 
 * @author synapticloop
 */

public class B2DownloadFileById {

	public B2DownloadFileById() {
		
	}
}
