package synapticloop.b2.request;

// - - - - thoughtfully generated by synapticloop backblaze-b2-java-api - - - - 
//          with the use of synapticloop templar templating language
//                    (java-create-api.templar)

/**
 * <p>Gets information about one file stored in B2.</p>
 * 
 * 
 * This is the interaction class for the <strong>b2_get_file_info</strong> api calls, this was automatically
 * generated from the backblaze api documentation - which can be found here:
 * <a href="http://www.backblaze.com/b2/docs/b2_get_file_info.html">http://www.backblaze.com/b2/docs/b2_get_file_info.html</a>
 * 
 * @author synapticloop
 */

public class B2GetFileInfo {

	public B2GetFileInfo() {
		
	}
}
