package synapticloop.b2.request;

// - - - - thoughtfully generated by synapticloop backblaze-b2-java-api - - - - 
//          with the use of synapticloop templar templating language
//                    (java-create-api.templar)

/**
 * <p>Hides a file so that downloading by name will not find the file, but previous versions of the file are still stored. See File Versions about what it means to hide a file.</p>
 * 
 * 
 * This is the interaction class for the <strong>b2_hide_file</strong> api calls, this was automatically
 * generated from the backblaze api documentation - which can be found here:
 * <a href="http://www.backblaze.com/b2/docs/b2_hide_file.html">http://www.backblaze.com/b2/docs/b2_hide_file.html</a>
 * 
 * @author synapticloop
 */

public class B2HideFile {

	public B2HideFile() {
		
	}
}
