package synapticloop.b2.request;

// - - - - thoughtfully generated by synapticloop backblaze-b2-java-api - - - - 
//          with the use of synapticloop templar templating language
//                    (java-create-api.templar)

/**
 * <p>Lists the names of all files in a bucket, starting at a given name.</p>
 * 
 * <p>This call returns at most 1000 file names, but it can be called repeatedly to scan through all of the file names in a bucket. Each time you call, it returns an "endFileName" that can be used as the starting point for the next call.</p>
 * <p>There may be many file versions for the same name, but this call will return each name only once. If you want all of the versions, use b2_list_file_versions instead.</p>
 * <p>To go through all of the file names in a bucket, use a loop like this:</p>
 * 
 * 
 * This is the interaction class for the <strong>b2_list_file_names</strong> api calls, this was automatically
 * generated from the backblaze api documentation - which can be found here:
 * <a href="http://www.backblaze.com/b2/docs/b2_list_file_names.html">http://www.backblaze.com/b2/docs/b2_list_file_names.html</a>
 * 
 * @author synapticloop
 */

public class B2ListFileNames {

	public B2ListFileNames() {
		
	}
}
