package synapticloop.b2.request;

// - - - - thoughtfully generated by synapticloop backblaze-b2-java-api - - - - 
//          with the use of synapticloop templar templating language
//                    (java-create-api.templar)

/**
 * <p>Lists all of the versions of all of the files contained in one bucket, in alphabetical order by file name, and by reverse of date/time uploaded for versions of files with the same name.</p>
 * 
 * 
 * This is the interaction class for the <strong>b2_list_file_versions</strong> api calls, this was automatically
 * generated from the backblaze api documentation - which can be found here:
 * <a href="http://www.backblaze.com/b2/docs/b2_list_file_versions.html">http://www.backblaze.com/b2/docs/b2_list_file_versions.html</a>
 * 
 * @author synapticloop
 */

public class B2ListFileVersions {

	public B2ListFileVersions() {
		
	}
}
